.php:
  before_script:
    - cp .env.gitlab .env
    - composer self-update
    - composer install --prefer-dist --no-interaction -n
    - php artisan key:generate
    - php artisan cache:clear
    - php artisan passport:keys
    - chmod 600 storage/oauth-*.key
